/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Adminde.java
 *
 * Created on Dec 27, 2022, 9:44:02 AM
 */
package dbms;

import static dbms.orgde.O1;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import java.util.logging.Level;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LENOVO
 */
public class Adminde extends javax.swing.JFrame {
     public Connection con;
    PreparedStatement pst;
    Statement sss;
   String Severity;

    /** Creates new form Adminde */
    public Adminde() {
        initComponents();
        Dimension sz=Toolkit.getDefaultToolkit().getScreenSize();
        this.setSize(sz.width,sz.height);
        
        jPanel2.setVisible(false);
         Connect();
         adminid();
         groupradio();
         table_update();
    }
    public void Connect()
    {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            try{
                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/sms","root","oracle");
                //System.out.println("connected");
            } catch (SQLException ex) {
            java.util.logging.Logger.getLogger(orgde.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        } catch (ClassNotFoundException ex) {
            //Logger.getLogger(orgde.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    public void adminid(){
        try {
            pst = con.prepareStatement("select Emp_ID from employee where Status='Inactive'and Org_ID=?");
             pst.setInt(1, Integer.parseInt(admin.u3.getText()));
             ResultSet rs=pst.executeQuery();
             
              
             
             rs=pst.executeQuery();
             
             while(rs.next()){

                 int Emp_ID=rs.getInt("Emp_ID");
                 a2.addItem(Emp_ID);
                 //int SID=rs.getInt("SID");
                 //a3.addItem(SID); 
             }
            
        } catch (Exception e) {
            
            JOptionPane.showMessageDialog(null,e);
        }
        
    }
    /*public void sid(){
        try {
            pst = con.prepareStatement("select Emp_ID from employee where Status='Inactive' and Org_ID=?");
             pst.setInt(1, Integer.parseInt(admin.u3.getText()));
             ResultSet rs=pst.executeQuery();
             
              
             
             rs=pst.executeQuery();
             
             while(rs.next()){

                 int Emp_ID=rs.getInt("Emp_ID");
                 a2.addItem(Emp_ID);
             }
            
        } catch (Exception e) {
            
            JOptionPane.showMessageDialog(null,e);
        }

    }*/
     private void table_update()
    {
        int CC;
        try {
            pst = con.prepareStatement("SELECT * from admin,employee where admin.Emp_ID=employee.Emp_ID and Org_ID="+Integer.parseInt(admin.orgid));
            ResultSet Rs= pst.executeQuery();
            
            ResultSetMetaData RSMD = Rs.getMetaData();
            CC = RSMD.getColumnCount();
            DefaultTableModel DFT = (DefaultTableModel) adminde.getModel();
            
            DFT.setRowCount(0);
            
            while (Rs.next()) {
                Vector v2 = new Vector();
                for(int i=1;i<=CC;i++){
                   // v2.add(Rs.getInt("Org_ID"));
                    v2.add(Rs.getString("Emp_ID"));
                   // v2.add(Rs.getString("SID"));
                   
                    v2.add(Rs.getString("ServerFailedDate"));
                     v2.add(Rs.getString("Severity")); 
                    v2.add(Rs.getString("Reason"));
                }
                DFT.addRow(v2);    
            }
            }catch(Exception e){
                System.out.println(e);
                
            }
        }
    public void groupradio()
    {
        buttonGroup1.add(Minor);
        buttonGroup1.add(Major);
        buttonGroup1.add(Critical);
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        a2 = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Minor = new javax.swing.JRadioButton();
        Major = new javax.swing.JRadioButton();
        Critical = new javax.swing.JRadioButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        a6 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Notify = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        insert1 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        adminde = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setMinimumSize(new java.awt.Dimension(1366, 768));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Bodoni MT Black", 3, 36)); // NOI18N
        jLabel2.setText("Inactive Server Details");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(50, 20, 480, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Emp ID :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(130, 120, 70, 17);

        a2.setEditable(true);
        jPanel1.add(a2);
        a2.setBounds(200, 102, 130, 40);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Server Failed Date :");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(60, 170, 140, 17);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Reason :");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(130, 270, 70, 17);

        Minor.setBackground(new java.awt.Color(255, 255, 153));
        Minor.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Minor.setText("Minor");
        jPanel1.add(Minor);
        Minor.setBounds(200, 220, 90, 19);

        Major.setBackground(new java.awt.Color(255, 153, 0));
        Major.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Major.setText("Major");
        Major.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MajorActionPerformed(evt);
            }
        });
        jPanel1.add(Major);
        Major.setBounds(310, 220, 98, 20);

        Critical.setBackground(new java.awt.Color(255, 0, 51));
        Critical.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Critical.setText("Critical");
        Critical.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CriticalActionPerformed(evt);
            }
        });
        jPanel1.add(Critical);
        Critical.setBounds(430, 220, 90, 19);
        jPanel1.add(jDateChooser1);
        jDateChooser1.setBounds(200, 162, 150, 30);

        a6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a6ActionPerformed(evt);
            }
        });
        jPanel1.add(a6);
        a6.setBounds(200, 260, 130, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Severity:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(130, 220, 80, 17);

        Notify.setBackground(new java.awt.Color(0, 0, 0));
        Notify.setForeground(new java.awt.Color(255, 255, 255));
        Notify.setText("Notify");
        Notify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NotifyActionPerformed(evt);
            }
        });
        jPanel1.add(Notify);
        Notify.setBounds(870, 510, 190, 70);

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("View");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(450, 330, 100, 22);

        insert1.setBackground(new java.awt.Color(0, 0, 0));
        insert1.setForeground(new java.awt.Color(255, 255, 255));
        insert1.setText("Insert");
        insert1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insert1ActionPerformed(evt);
            }
        });
        jPanel1.add(insert1);
        insert1.setBounds(200, 330, 100, 22);

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Delete");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(320, 330, 110, 22);

        adminde.setBackground(new java.awt.Color(153, 153, 153));
        adminde.setForeground(new java.awt.Color(255, 255, 255));
        adminde.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Emp_ID", "ServerFailedDateandTime", "Severity", "Reason"
            }
        ));
        adminde.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                admindeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(adminde);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(30, 390, 690, 220);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ADM1.jpg"))); // NOI18N
        jPanel1.add(jLabel6);
        jLabel6.setBounds(750, 30, 610, 550);

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\DELL 3493\\OneDrive\\Desktop\\background\\w12a (1).jpg")); // NOI18N
        jLabel1.setMinimumSize(new java.awt.Dimension(1366, 768));
        jPanel1.add(jLabel1);
        jLabel1.setBounds(-100, 10, 1360, 770);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1366, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 768, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NotifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NotifyActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Notified");
        dispose();
       org a=new org();
       a.setVisible(true);
       Notify.setVisible(true);
    }//GEN-LAST:event_NotifyActionPerformed

    private void admindeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_admindeMouseClicked
        // TODO add your handling code here:
         DefaultTableModel DFT = (DefaultTableModel)adminde.getModel();
        int selectedIndex = adminde.getSelectedRow();

       //String Org_ID=DFT.getValueAt(selectedIndex,0).toString();
       String  Emp_ID=DFT.getValueAt(selectedIndex,0).toString();
       //String  SID=DFT.getValueAt(selectedIndex,2).toString();
      
       String ServerFailedDateTime= DFT.getValueAt(selectedIndex,1).toString();
       String  Severity=DFT.getValueAt(selectedIndex,2).toString();
       if(Severity.equals("Minor"))
        {
            Minor.setSelected(true);
        }
       else if(Severity.equals("Major"))
        {
            Major.setSelected(true);
        }
        else
        {
            Critical.setSelected(true);
        }
        String  Reason=DFT.getValueAt(selectedIndex,3).toString();
        
       //a1.setText(Org_ID);
       a2.setSelectedItem(Emp_ID);
       //a3.setSelectedItem(SID);
      
       //a5.setText(ServerFailedDateTime);
       // a4.setSelectedItem(Status);
       a6.setText(Reason);
    }//GEN-LAST:event_admindeMouseClicked

    private void insert1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insert1ActionPerformed
         jPanel2.setVisible(true);
  
        try {
            // TODO add your handling code here
            String Emp_ID,ServerFailedDateTime, Reason;
            
          // Org_ID=a1.getText();
           Emp_ID=a2.getSelectedItem().toString();
           
          // SID=a3.getSelectedItem().toString();
           // Status=a4.getSelectedItem().toString();
            Date d1 =jDateChooser1.getDate();
    SimpleDateFormat formatter = new SimpleDateFormat("YYYY-MM-dd HH:mm:ss");
   // System.out.println(formatter.format(d1));
            ServerFailedDateTime = formatter.format(d1);
            Reason = a6.getText(); 
            if(Minor.isSelected())
                Severity="Minor";
            else if(Major.isSelected())
                Severity="Major";
            else if(Critical.isSelected())
                Severity="Critical";
           
                      
            
            pst = con.prepareStatement("insert into admin(Emp_ID,ServerFailedDate,Severity,Reason)values(?,?,?,?)");
           //pst.setString(1, Emp_ID);
         // pst.setInt(2, Integer.parseInt(a1.getText()));
          // pst.setString(2, Org_ID);
         pst.setInt(1, Integer.parseInt(a2.getSelectedItem().toString()));
           //pst.setString(3, SID);
         //  pst.setInt(3, Integer.parseInt(a3.getSelectedItem().toString()));
           //pst.setString(4, Status);
            pst.setString(2,ServerFailedDateTime);
            pst.setString(3,Severity);
            pst.setString(4, Reason);
            
            
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Record Saved");
            table_update();
            //a1.setText();
           a2.setSelectedItem("");
           // a3.setSelectedItem("");
            //a4.setSelectedItem("");
            //a5.setText("");
            if(Minor.isSelected())
            {
                Severity="Minor";
            }
            else if(Major.isSelected())
            {
                Severity="Major";
            }
            else{
                Severity="Critical";
            }
            a6.setText("");
            a2.requestFocus();

        } catch (SQLException ex) {
            
            if(ex.getSQLState().equals("02000"))
            {
                JOptionPane.showMessageDialog(this, "Notification Date cannot exceed Current Date");
                return;
            }
            //System.out.print("eee");
            ex.printStackTrace();
        }  
    }//GEN-LAST:event_insert1ActionPerformed

    private void MajorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MajorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MajorActionPerformed

    private void CriticalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CriticalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CriticalActionPerformed

    private void a6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {                                     
            // TODO add your handling code here
         
        DefaultTableModel DFT = (DefaultTableModel) adminde.getModel();
        int selectedIndex = adminde.getSelectedRow();
        
        int Emp_ID=Integer.parseInt(DFT.getValueAt(selectedIndex,0).toString());
            pst = con.prepareStatement("delete from admin where Emp_ID=?");
            pst.setInt(1, Integer.parseInt(a2.getSelectedItem().toString()));
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this,"Record deleted");
            table_update();
            a2.setSelectedItem("");
           // a5.setText("");
            a6.setText("");
            
            a2.requestFocus();  
         } catch (Exception ex) {
            //Logger.getLogger(orgde.class.getName()).log(Level.SEVERE, null, ex);
            ex.printStackTrace();
         }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jPanel2.setVisible(true);
        table_update();      
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Adminde().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Critical;
    private javax.swing.JRadioButton Major;
    private javax.swing.JRadioButton Minor;
    private javax.swing.JButton Notify;
    private javax.swing.JComboBox a2;
    private javax.swing.JTextField a6;
    private javax.swing.JTable adminde;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton insert1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
