/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * notify.java
 *
 * Created on Dec 27, 2022, 7:43:01 PM
 */
package dbms;

import static dbms.empde.e2;
import static dbms.orgde.O1;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import java.util.logging.Level;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LENOVO
 */
public class notify extends javax.swing.JFrame {

    /** Creates new form notify */
    public Connection con;
    PreparedStatement pst;
    public notify() {
        initComponents();
         Dimension sz=Toolkit.getDefaultToolkit().getScreenSize();
        this.setSize(sz.width,sz.height);
        
        Connect();
        table_update();
        Orgid();
    }
    public void Connect() {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            try {
                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/sms", "root", "oracle");
            } catch (SQLException ex) {
                java.util.logging.Logger.getLogger(orgde.class.getName()).log(Level.SEVERE, null, ex);
            }

        } catch (ClassNotFoundException ex) {
            //Logger.getLogger(orgde.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public void Orgid(){
        try {
            
            pst = con.prepareStatement("select Org_ID from organization ");
             ResultSet rs=pst.executeQuery();
             
             rs=pst.executeQuery();
             
             while(rs.next()){

                 int Org_ID=rs.getInt("Org_ID");
                 n1.addItem(Org_ID);
             }
            
        } catch (Exception e) {
            
            JOptionPane.showMessageDialog(null,e);
        }
    }
    private void table_update() {
        int CC;
        try {
            pst = con.prepareStatement("SELECT * FROM notification_team");
            ResultSet Rs = pst.executeQuery();

            ResultSetMetaData RSMD = Rs.getMetaData();
            CC = RSMD.getColumnCount();
            DefaultTableModel DFT = (DefaultTableModel) notde.getModel();
            DFT.setRowCount(0);

            while (Rs.next()) {
                Vector v2 = new Vector();
                for (int i = 1; i <= CC; i++) {
                    v2.add(Rs.getInt("Org_ID"));
                    v2.add(Rs.getString("NotifID"));
                    v2.add(Rs.getString("Password"));
                    
                }
                DFT.addRow(v2);
            }
        } catch (Exception e) {

        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        notde = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        DELETE = new javax.swing.JButton();
        Insert = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        n1 = new javax.swing.JComboBox();
        n2 = new javax.swing.JTextField();
        n3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setMaximumSize(new java.awt.Dimension(1366, 768));
        jPanel1.setLayout(null);

        notde.setBackground(new java.awt.Color(51, 51, 51));
        notde.setForeground(new java.awt.Color(0, 204, 204));
        notde.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Org_ID", "Notify_ID", "Password"
            }
        ));
        notde.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                notdeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(notde);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 710, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(460, 80, 710, 420);

        jLabel2.setBackground(new java.awt.Color(255, 153, 255));
        jLabel2.setFont(new java.awt.Font("Bodoni MT Black", 3, 36)); // NOI18N
        jLabel2.setText("NOTIFICATION DETAILS");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(50, 20, 540, 50);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Org_ID:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(90, 150, 90, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Notify_ID:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(70, 197, 100, 30);

        DELETE.setBackground(new java.awt.Color(0, 0, 0));
        DELETE.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        DELETE.setForeground(new java.awt.Color(0, 204, 204));
        DELETE.setText("Delete");
        DELETE.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255)));
        DELETE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DELETEActionPerformed(evt);
            }
        });
        jPanel1.add(DELETE);
        DELETE.setBounds(260, 360, 110, 30);

        Insert.setBackground(new java.awt.Color(0, 0, 0));
        Insert.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Insert.setForeground(new java.awt.Color(0, 204, 204));
        Insert.setText("Insert");
        Insert.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255)));
        Insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertActionPerformed(evt);
            }
        });
        jPanel1.add(Insert);
        Insert.setBounds(140, 360, 110, 30);

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 204, 204));
        jButton2.setText("Logout");
        jButton2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255)));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(130, 410, 260, 30);

        n1.setBackground(new java.awt.Color(0, 0, 0));
        n1.setForeground(new java.awt.Color(255, 255, 255));
        n1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255)));
        n1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n1ActionPerformed(evt);
            }
        });
        jPanel1.add(n1);
        n1.setBounds(180, 150, 170, 30);

        n2.setBackground(new java.awt.Color(0, 0, 0));
        n2.setForeground(new java.awt.Color(255, 255, 255));
        n2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255)));
        n2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n2ActionPerformed(evt);
            }
        });
        jPanel1.add(n2);
        n2.setBounds(180, 200, 170, 30);

        n3.setBackground(new java.awt.Color(0, 0, 0));
        n3.setForeground(new java.awt.Color(255, 255, 255));
        n3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255)));
        n3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n3ActionPerformed(evt);
            }
        });
        jPanel1.add(n3);
        n3.setBounds(180, 250, 170, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Password:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(70, 247, 100, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 204));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/emlolo.jpg"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255)));
        jPanel1.add(jLabel1);
        jLabel1.setBounds(-10, 0, 1380, 1010);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1370, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 835, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void n2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_n2ActionPerformed

    private void n3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_n3ActionPerformed

    private void InsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertActionPerformed
        // TODO add your handling code here:
         jPanel2.setVisible(true);
  
        try {
            // TODO add your handling code here
            String NotifID,Password;

            //Org_ID = n1.getText();
            NotifID = n2.getText();
            Password = n3.getText();
            //Status= (String) O5.getSelectedItem();
            Statement stmt=con.createStatement();
            ResultSet res=stmt.executeQuery("select * from notification_team where Org_ID="+Integer.parseInt(n1.getSelectedItem().toString()));
            if(res.next())
            {
                 JOptionPane.showMessageDialog(this, "Notify id already exists for this organization");
                 return;
            }
            pst = con.prepareStatement("insert into notification_team(Org_ID,NotifID,Password)values(?,?,?)");
            pst.setInt(1, Integer.parseInt(n1.getSelectedItem().toString()));
            pst.setString(2,NotifID);
            pst.setString(3, Password);           
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Record Saved");
            
            table_update();

            n2.setText("");
            n3.setText("");
            n1.requestFocus();

        } catch (SQLException ex) {
            ex.printStackTrace();
        }  
    }//GEN-LAST:event_InsertActionPerformed

    private void DELETEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DELETEActionPerformed
        // TODO add your handling code here:
        try {
            DefaultTableModel DFT=(DefaultTableModel) notde.getModel();
            int selectedIndex=notde.getSelectedRow();
            int Org_ID=Integer.parseInt(DFT.getValueAt(selectedIndex,1).toString());

            pst=con.prepareStatement("delete from notification_team where Org_ID=?");
           pst.setInt(1,Integer.parseInt(n1.getSelectedItem().toString()));
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this,"Record deleted");
            table_update();
            
            //n1.setSelectedItem("");
     
            n2.setText("");
            n3.setText("");
            n1.requestFocus();
        } catch (Exception ex) {
            ex.printStackTrace();
        } 
    }//GEN-LAST:event_DELETEActionPerformed

    private void notdeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_notdeMouseClicked
        // TODO add your handling code here:
        DefaultTableModel DFT = (DefaultTableModel)notde.getModel();
        int selectedIndex = notde.getSelectedRow();

       String Org_ID=DFT.getValueAt(selectedIndex,0).toString();
       String  NotifID=DFT.getValueAt(selectedIndex,1).toString();
       String  Password=DFT.getValueAt(selectedIndex,2).toString();
       
              for(int i=0;i<n1.getItemCount();i++)
        {
           // System.out.println(n1.getItemAt(i)+","+Org_ID);
            if(n1.getItemAt(i).toString().equals(Org_ID))
            {
                n1.setSelectedIndex(i);
                break;
            }
        }        
       //n1.setSelectedItem(Org_ID);
       n2.setText(NotifID);
       n3.setText(Password);
       
    }//GEN-LAST:event_notdeMouseClicked

    private void n1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_n1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         dispose();
        orgde h=new orgde();
        h.setVisible(true);
        jButton2.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new notify().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DELETE;
    private javax.swing.JButton Insert;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox n1;
    private javax.swing.JTextField n2;
    private javax.swing.JTextField n3;
    private javax.swing.JTable notde;
    // End of variables declaration//GEN-END:variables
}
