/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * org.java
 *
 * Created on Dec 23, 2022, 2:56:05 PM
 */
package dbms;

import javax.swing.JFrame;
/**
 *
 * @author LENOVO
 */
public class org extends javax.swing.JFrame {

    /** Creates new form org */
    public org() {
        initComponents();
        
    }
    orgde Organization = new orgde();
    //emplo user=new emplo();
    //admin admin1=new admin();
    //notify notify1=new notify();

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        ORGANIZATION = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        user = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        admin1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        notify1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0,80));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 320, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(290, 160, 540, 320);

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Bodoni MT Black", 3, 36)); // NOI18N
        jLabel2.setText("SERVER  NOTIFICATION  MANAGEMENT  SYSTEM");
        jLabel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 51, 204), new java.awt.Color(51, 0, 255)));
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabel2);
        jLabel2.setBounds(60, 50, 1110, 70);

        ORGANIZATION.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ORGANIZATION.setForeground(new java.awt.Color(102, 0, 0));
        ORGANIZATION.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ORG.jpg"))); // NOI18N
        ORGANIZATION.setAlignmentY(1.2F);
        ORGANIZATION.setBorder(new javax.swing.border.MatteBorder(null));
        ORGANIZATION.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ORGANIZATION.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        ORGANIZATION.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ORGANIZATIONActionPerformed(evt);
            }
        });
        jPanel1.add(ORGANIZATION);
        ORGANIZATION.setBounds(360, 210, 400, 230);

        jLabel1.setBackground(new java.awt.Color(102, 102, 102));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user.jpeg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(350, 200, 420, 250);

        user.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        user.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user.jpg"))); // NOI18N
        user.setText("USER");
        user.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 51, 204)));
        user.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userActionPerformed(evt);
            }
        });
        jPanel1.add(user);
        user.setBounds(130, 530, 240, 130);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user.jpeg"))); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(120, 520, 260, 150);

        admin1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        admin1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/admin2.jpg"))); // NOI18N
        admin1.setText("ADMIN");
        admin1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 204)));
        admin1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        admin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admin1ActionPerformed(evt);
            }
        });
        jPanel1.add(admin1);
        admin1.setBounds(450, 530, 270, 130);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user.jpeg"))); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(440, 520, 290, 150);

        notify1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        notify1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/NOTIFY1.jpg"))); // NOI18N
        notify1.setText("NOTIFY TEAM");
        notify1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 51, 204)));
        notify1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        notify1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notify1ActionPerformed(evt);
            }
        });
        jPanel1.add(notify1);
        notify1.setBounds(820, 530, 250, 130);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user.jpeg"))); // NOI18N
        jPanel1.add(jLabel6);
        jLabel6.setBounds(810, 520, 270, 150);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/w3 (2).jpg"))); // NOI18N
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabel3);
        jLabel3.setBounds(0, -530, 1320, 1260);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1328, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 766, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ORGANIZATIONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ORGANIZATIONActionPerformed
        
       // TODO add your handling code here:
          dispose();
        Super h=new Super();
        h.setVisible(true);
        ORGANIZATION.setVisible(true);
    }//GEN-LAST:event_ORGANIZATIONActionPerformed

    private void userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userActionPerformed
        // TODO add your handling code here:
        dispose();
        emplo h=new emplo();
        h.setVisible(true);
        user.setVisible(true); 
    }//GEN-LAST:event_userActionPerformed

    private void admin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admin1ActionPerformed
        // TODO add your handling code here:
        dispose();
        admin h=new admin();
        h.setVisible(true);
        admin1.setVisible(true);
    }//GEN-LAST:event_admin1ActionPerformed

    private void notify1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notify1ActionPerformed
        // TODO add your handling code here:
        dispose();
        notifylo h=new notifylo();
        h.setVisible(true);
        notify1.setVisible(true);
    }//GEN-LAST:event_notify1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new org().setVisible(true);
            }
        });
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ORGANIZATION;
    private javax.swing.JButton admin1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton notify1;
    private javax.swing.JButton user;
    // End of variables declaration//GEN-END:variables
}
