package dbms;

import java.awt.Dimension;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.io.ObjectInputFilter.Status;
import java.lang.System.Logger;
import java.sql.*;
import java.util.Vector;
import java.util.logging.Level;
import javax.swing.JOptionPane;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LENOVO
 */
public class orgde extends javax.swing.JFrame {

    public Connection con;
    PreparedStatement pst;
    Statement sss;
    public orgde() {
        initComponents();
        Dimension sz=Toolkit.getDefaultToolkit().getScreenSize();
        this.setSize(sz.width,sz.height);
        
        jPanel2.setVisible(false);
        Connect();
        table_update();
        //table_search();
    }
  
    //empde Submit = new empde();

    public void Connect() {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            try {
                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/sms", "root", "oracle");
            } catch (SQLException ex) {
                java.util.logging.Logger.getLogger(orgde.class.getName()).log(Level.SEVERE, null, ex);
            }

        } catch (ClassNotFoundException ex) {
            //Logger.getLogger(orgde.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void table_update() {
        int CC;
        try {
            pst = con.prepareStatement("SELECT * FROM organization");
            ResultSet Rs = pst.executeQuery();

            ResultSetMetaData RSMD = Rs.getMetaData();
            CC = RSMD.getColumnCount();
            DefaultTableModel DFT = (DefaultTableModel) orgde.getModel();
            DFT.setRowCount(0);

            while (Rs.next()) {
                Vector v2 = new Vector();
                for (int i = 1; i <= CC; i++) {
                    v2.add(Rs.getInt("Org_ID"));
                    v2.add(Rs.getString("Org_Name"));
                    v2.add(Rs.getString("Address"));
                    v2.add(Rs.getString("Contact"));
                    v2.add(Rs.getString("Status"));
                }
                DFT.addRow(v2);
            }
        } catch (Exception e) {

        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        O1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        O2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        O3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        O4 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        O5 = new javax.swing.JComboBox();
        Insert = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        update = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        view = new javax.swing.JButton();
        O7 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        search = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        orgde = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Bodoni MT Black", 3, 24)); // NOI18N
        jLabel2.setText("ORGANIZATION DETAILS");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(40, 10, 400, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Org_ID :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(50, 90, 80, 17);

        O1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        O1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                O1ActionPerformed(evt);
            }
        });
        jPanel1.add(O1);
        O1.setBounds(140, 80, 130, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Org_Name :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 120, 110, 30);

        O2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(O2);
        O2.setBounds(140, 118, 130, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Address :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(50, 157, 90, 30);

        O3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(O3);
        O3.setBounds(140, 160, 130, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Contact :");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(50, 200, 90, 22);

        O4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(O4);
        O4.setBounds(140, 198, 130, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("             Status:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(0, 240, 140, 30);

        O5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Active", "Inactive" }));
        O5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(O5);
        O5.setBounds(140, 240, 90, 30);

        Insert.setBackground(new java.awt.Color(0, 0, 0));
        Insert.setForeground(new java.awt.Color(255, 255, 255));
        Insert.setText("Insert");
        Insert.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertActionPerformed(evt);
            }
        });
        jPanel1.add(Insert);
        Insert.setBounds(20, 280, 80, 20);

        Delete.setBackground(new java.awt.Color(0, 0, 0));
        Delete.setForeground(new java.awt.Color(255, 255, 255));
        Delete.setText("Delete");
        Delete.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });
        jPanel1.add(Delete);
        Delete.setBounds(120, 280, 80, 20);

        update.setBackground(new java.awt.Color(0, 0, 0));
        update.setForeground(new java.awt.Color(255, 255, 255));
        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        jPanel1.add(update);
        update.setBounds(210, 280, 90, 22);

        jButton1.setBackground(new java.awt.Color(0, 204, 204));
        jButton1.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jButton1.setText(" Employee Details");
        jButton1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(960, 40, 160, 60);

        view.setBackground(new java.awt.Color(0, 0, 0));
        view.setForeground(new java.awt.Color(255, 255, 255));
        view.setText("View");
        view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewActionPerformed(evt);
            }
        });
        jPanel1.add(view);
        view.setBounds(320, 280, 80, 22);

        O7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(O7);
        O7.setBounds(410, 88, 110, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Enter Org_ID:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(300, 90, 110, 30);

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Logout");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(180, 530, 240, 50);

        jButton2.setBackground(new java.awt.Color(0, 204, 204));
        jButton2.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jButton2.setText("Notification  Team Details");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(620, 40, 270, 60);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/1.jpeg"))); // NOI18N
        jPanel1.add(jLabel8);
        jLabel8.setBounds(610, -110, 590, 790);

        search.setBackground(new java.awt.Color(0, 0, 0));
        search.setForeground(new java.awt.Color(255, 255, 255));
        search.setText("Search");
        search.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        jPanel1.add(search);
        search.setBounds(380, 140, 130, 20);

        orgde.setBackground(new java.awt.Color(0, 0, 0));
        orgde.setForeground(new java.awt.Color(102, 102, 102));
        orgde.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Org_ID", "Org_Name", "Address", "Contact", "Status"
            }
        ));
        orgde.setName("organization"); // NOI18N
        orgde.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                orgdeMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(orgde);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(20, 310, 580, 180);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/w6a.jpg"))); // NOI18N
        jLabel9.setMaximumSize(new java.awt.Dimension(4000, 4000));
        jLabel9.setPreferredSize(new java.awt.Dimension(4000, 4000));
        jPanel1.add(jLabel9);
        jLabel9.setBounds(-310, -320, 2040, 1170);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1215, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 925, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        
        try {                                     
            // TODO add your handling code here
         
        DefaultTableModel DFT = (DefaultTableModel) orgde.getModel();
        int selectedIndex = orgde.getSelectedRow();
        
        int Org_ID=Integer.parseInt(DFT.getValueAt(selectedIndex,0).toString());
            pst = con.prepareStatement("delete from organization where Org_ID=?");
            pst.setInt(1,Integer.parseInt(O1.getText()));
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this,"Record deleted");
            table_update();
            O1.setText("");
            O2.setText("");
            O3.setText("");
            O4.setText("");
            O2.requestFocus();  
         } catch (Exception ex) {
            //Logger.getLogger(orgde.class.getName()).log(Level.SEVERE, null, ex);
            ex.printStackTrace();
         }
    }//GEN-LAST:event_DeleteActionPerformed

    private void orgdeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orgdeMouseClicked
        DefaultTableModel DFT = (DefaultTableModel)orgde.getModel();
        int selectedIndex = orgde.getSelectedRow();

       String Org_ID=DFT.getValueAt(selectedIndex,0).toString();
       String  Org_Name=DFT.getValueAt(selectedIndex,1).toString();
       String  Address=DFT.getValueAt(selectedIndex,2).toString();
       String  Contact=DFT.getValueAt(selectedIndex,3).toString();
       String Status= DFT.getValueAt(selectedIndex,4).toString();
        
       O1.setText(Org_ID);
       O2.setText(Org_Name);
       O3.setText(Address);
       O4.setText(Contact);
       O5.setSelectedItem(Status);
    }//GEN-LAST:event_orgdeMouseClicked

    private void InsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertActionPerformed
        jPanel2.setVisible(true);
  
        try {
            // TODO add your handling code here
            String Org_Name, Address, Contact,Status;

            Org_Name = O2.getText();
            Address = O3.getText();
            Contact = O4.getText();
            Status= (String) O5.getSelectedItem();

            pst = con.prepareStatement("insert into organization(Org_ID,Org_Name,Address,Contact,Status)values(?,?,?,?,?)");
            pst.setInt(1, Integer.parseInt(O1.getText()));
            pst.setString(2, Org_Name);
            pst.setString(3, Address);
            pst.setString(4, Contact);
            pst.setString(5, O5.getSelectedItem().toString());
            
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Record Saved");
            
            table_update();

            O2.setText("");
            O3.setText("");
            O4.setText("");
            O2.requestFocus();

        } catch (SQLException ex) {
            
            ex.printStackTrace();
        }  
    }//GEN-LAST:event_InsertActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       // Submit.setVisible(true);// TODO add your handling code here:
       dispose();
       empde o=new empde();
       o.setVisible(true);
       //jButton1.setVisible(true);
      /* empde x=new empde();
       empde.e2.setSelectedItem(orgde.O1.getText());
                  // user.Empid.setText(emplo.u1.getText());
                    x.setVisible(true);*/
                    
       
    }//GEN-LAST:event_jButton1ActionPerformed
    public void table_search()
    {
        int CC;
        try {
            pst=con.prepareStatement("select * from organization where Org_ID=?");
             int Org_ID=Integer.parseInt(O7.getText());
            System.out.println(Org_ID);
            pst.setInt(1,Org_ID);
            ResultSet Rs=pst.executeQuery();
           
            ResultSetMetaData RSMD = (ResultSetMetaData) Rs.getMetaData();
            CC = RSMD.getColumnCount();
            DefaultTableModel DFT = (DefaultTableModel) orgde.getModel();
            int selectedIndex = orgde.getSelectedRow();
           
            DFT.setRowCount(0);

            while (Rs.next()) {
                Vector v2 = new Vector();
                for (int i = 1; i <= CC; i++) {
                    v2.add(Rs.getInt("Org_ID"));
                    v2.add(Rs.getString("Org_Name"));
                    v2.add(Rs.getString("Address"));
                    v2.add(Rs.getString("Contact"));
                    v2.add(Rs.getString("Status"));
                }
                DFT.addRow(v2);
            }
        } catch (Exception e) {
               System.out.println("exception1");
        e.printStackTrace();
        }
    }
    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        
        try{
            pst=con.prepareStatement("select * from organization where Org_ID=?");
             int Org_ID=Integer.parseInt(O7.getText());
            System.out.println(Org_ID);
            pst.setInt(1,Org_ID);
            ResultSet rs=pst.executeQuery();
    
            if(rs.next()==false)
            {
                JOptionPane.showMessageDialog(this,"Sorry record not found");
                O1.setText("");
                O2.setText("");
            O3.setText("");
            O4.setText("");
            O2.requestFocus();
            }
            else{
                O1.setText(rs.getString("Org_ID"));
                O2.setText(rs.getString("Org_Name"));
                O3.setText(rs.getString("Address"));
                O4.setText(rs.getString("Contact"));
                O5.setSelectedItem(rs.getString("Status"));
                pst.setString(5, O5.getSelectedItem().toString());
            }   
        }catch(Exception e){
             System.out.println("exception2"+e);
           // System.out.println(e);
        }
         jPanel2.setVisible(true);
            table_search();         
    }//GEN-LAST:event_searchActionPerformed

    private void viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewActionPerformed
        // TODO add your handling code here:
      jPanel2.setVisible(true);
        table_update();      
    }//GEN-LAST:event_viewActionPerformed

    private void O1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_O1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_O1ActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
         try {
           //Class.forName("com.mysql.cj.jdbc.Driver");
           //con=DriverManager.getConnection("jdbc:mysql://localhost/sms","root","oracle");
            String Org_Name,Address,Contact,Status;
  
            int row=orgde.getSelectedRow();
            String value=(orgde.getModel().getValueAt(row,0).toString());
           String query="update `organization` set Org_Name=?,Address=?,Contact=?,Status=? where Org_ID=?";
            pst=con.prepareStatement(query);
            //pst=con.prepareStatement("UPDATE `employee` SET `Emp_ID`='[value-1]',`Org_ID`='[value-2]',`FName`='[value-3]',`LName`='[value-4]',`Email`='[value-5]',`Phn_No`='[value-6]',`Type_Emp`='[value-7]',`SID`='[value-8]',`Status`='[value-9]',`password`='[value-10]' WHERE 1");
            
           //Emp_ID=e1.getText();
            //Org_ID=O1.getSelectedItem().toString();
            Org_Name=O2.getText();
            Address=O3.getText();
            Contact=O4.getText();
            Status=O5.getSelectedItem().toString();
          //  Type_Emp=Type_Emp.getSelectedItem().toString();
            
            
      
            pst=con.prepareStatement("update `organization` set Org_Name=?,Address=?,Contact=?,Status=? where Org_ID=?");
            
            //pst.setString(1,Emp_ID);
          pst.setInt(5, Integer.parseInt(O1.getText()));
           //String c;
           //c=Org_ID.getSelectedItem().toString();
            pst.setString(1, Org_Name);
            pst.setString(2,Address);
            pst.setString(3,Contact);
            pst.setString(4,Status);
            
            pst.executeUpdate();

            table_update();
              JOptionPane.showMessageDialog(this,"record updated");
             O1.setText("");
             O2.setText("");
             O3.setText("");
             O4.setText("");
             O5.setSelectedItem("");
            
             O1.requestFocus();
             
           
        
        } catch (SQLException ex) {
            //Logger.getLogger(empde.class.getName()).log(Level.SEVERE, null, ex);
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null,ex);
        } 
    }//GEN-LAST:event_updateActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         dispose();
       notify o=new notify();
       o.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         dispose();
        org h=new org();
        h.setVisible(true);
        jButton3.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
            //catch(Exception e) {}

        } catch (ClassNotFoundException ex) {
            ex.printStackTrace();
//java.util.Logging.Logger.getLogger(orgde.class .getName()).log(java.util.logging.Level.SEVERE,null,ex);
        } catch (IllegalAccessException ex) {
//java.util.Logging.Logger.getLogger(orgde.class .getName()).log(java.util.logging.Level.SEVERE,null,ex);
        } catch (InstantiationException ex) {
        } catch (UnsupportedLookAndFeelException ex) {
        }
        
        orgde obj1 = new orgde();
        obj1.show();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Delete;
    private javax.swing.JButton Insert;
    public static javax.swing.JTextField O1;
    public javax.swing.JTextField O2;
    public javax.swing.JTextField O3;
    public javax.swing.JTextField O4;
    public javax.swing.JComboBox O5;
    private javax.swing.JTextField O7;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable orgde;
    private javax.swing.JButton search;
    private javax.swing.JButton update;
    private javax.swing.JButton view;
    // End of variables declaration//GEN-END:variables
}
