/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dbms;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL 3493
 */
public class user extends javax.swing.JFrame {

     public Connection con;
    PreparedStatement pst;
    Statement sss;
    public user() {
        initComponents();
         Dimension sz=Toolkit.getDefaultToolkit().getScreenSize();
        this.setSize(sz.width,sz.height);
        
    Connect();
    groupradio();
    try{
    Statement st=con.createStatement();
    ResultSet rs=st.executeQuery("select * from employee where Emp_ID="+emplo.eid);
    if(rs.next())
    {
        Sid.setText(rs.getInt("SID")+"");
        Sid.setEditable(false);
    }
    }
    catch(Exception e)
    {
        e.printStackTrace();
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    public void Connect() {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            try {
                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/sms", "root", "oracle");
            } catch (SQLException ex) {
                java.util.logging.Logger.getLogger(orgde.class.getName()).log(Level.SEVERE, null, ex);
            }

        } catch (ClassNotFoundException ex) {
            //Logger.getLogger(orgde.class.getName()).log(Level.SEVERE, null, ex);
        }
        
       
    }
    
    public void groupradio()
    {
        buttonGroup1.add(Active);
        buttonGroup1.add(Inactive);
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Empid = new javax.swing.JTextField();
        Sid = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        logout = new javax.swing.JButton();
        u3 = new javax.swing.JButton();
        Active = new javax.swing.JRadioButton();
        Inactive = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Bodoni MT Black", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("USER  SERVER MODIFICATION DETAILS");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(40, 20, 680, 80);

        Empid.setEditable(false);
        Empid.setBackground(new java.awt.Color(255, 255, 255));
        Empid.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 204, 204), new java.awt.Color(0, 204, 204), new java.awt.Color(0, 204, 204), new java.awt.Color(0, 204, 204)));
        jPanel1.add(Empid);
        Empid.setBounds(180, 120, 220, 40);

        Sid.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 204, 204), new java.awt.Color(0, 204, 204), new java.awt.Color(0, 204, 204), new java.awt.Color(0, 204, 204)));
        Sid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SidActionPerformed(evt);
            }
        });
        jPanel1.add(Sid);
        Sid.setBounds(180, 190, 220, 40);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Server Status:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(40, 260, 100, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Emp_ID:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(70, 130, 70, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("SID:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(100, 200, 60, 20);

        logout.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        logout.setText("Logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        jPanel1.add(logout);
        logout.setBounds(200, 340, 130, 40);

        u3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        u3.setText("Update");
        u3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                u3ActionPerformed(evt);
            }
        });
        jPanel1.add(u3);
        u3.setBounds(410, 250, 130, 50);

        Active.setBackground(new java.awt.Color(0, 0, 0));
        Active.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Active.setForeground(new java.awt.Color(255, 255, 255));
        Active.setText("Active");
        jPanel1.add(Active);
        Active.setBounds(170, 260, 100, 30);

        Inactive.setBackground(new java.awt.Color(0, 0, 0));
        Inactive.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Inactive.setForeground(new java.awt.Color(255, 255, 255));
        Inactive.setText("Inactive");
        Inactive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InactiveActionPerformed(evt);
            }
        });
        jPanel1.add(Inactive);
        Inactive.setBounds(280, 260, 110, 30);

        jLabel3.setBackground(new java.awt.Color(0, 204, 204));
        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\DELL 3493\\OneDrive\\Desktop\\background\\ologo2.jpg")); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(630, 110, 640, 470);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user_1.jpg"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 204, 204), new java.awt.Color(0, 204, 204), new java.awt.Color(0, 204, 204), new java.awt.Color(0, 204, 204)));
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1500, 930);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1496, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 924, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SidActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_SidActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
       dispose();
       org o=new org();
       o.setVisible(true);
    }//GEN-LAST:event_logoutActionPerformed

    private void InactiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InactiveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InactiveActionPerformed

    private void u3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_u3ActionPerformed
        // TODO add your handling code here:
        String Status="";
         try {
             pst=con.prepareStatement("Update employee set status=? where Emp_ID=? and SID=? ");
             if(Active.isSelected()){
                Status="Active";
            }
            if(Inactive.isSelected()){
                Status="InActive";
            }
           pst.setString(1,Status);
           pst.setInt(2,Integer.parseInt(Empid.getText()));
           pst.setInt(3,Integer.parseInt(Sid.getText()));
             JOptionPane.showMessageDialog(this,"Updated Successfully");
           pst.executeUpdate();

         } catch (SQLException ex) {
             Logger.getLogger(user.class.getName()).log(Level.SEVERE, null, ex);
         }
        
    }//GEN-LAST:event_u3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new user().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Active;
    public static javax.swing.JTextField Empid;
    private javax.swing.JRadioButton Inactive;
    public static javax.swing.JTextField Sid;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton logout;
    private javax.swing.JButton u3;
    // End of variables declaration//GEN-END:variables
}
